Добавил функцию КаталогПустой
oscript-library/files-common pull request #12
Opened 2017-02-21 21:00 UTC by antowski

2017-02-21 22:08 UTC, nixel2007 approved these changes
Спасибо за пулл реквест! 

Есть в округе грамотеи? :) как с точки зрения языка правильнее - каталог пуст или каталог пустой (в связке с "Если")? 
Или вкусовщина?

2017-02-22 05:01 UTC, EvilBeaver commented
Мне кажется Пуст

22 Фев 2017 г. 1:08 пользователь "Nikita Gryzlov" <notifications@github.com>
написал:

> *@nixel2007* approved this pull request.
>
> Спасибо за пулл реквест!
>
> Есть в округе грамотеи? :) как с точки зрения языка правильнее - каталог
> пуст или каталог пустой (в связке с "Если")?
> Или вкусовщина?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/oscript-library/files-common/pull/12#pullrequestreview-23084674>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACiNGcC-tWwZ3zncTDiC9V0-wfA4Nms9ks5re2B3gaJpZM4MH2u1>
> .
>

2017-02-22 05:45 UTC, nixel2007 commented
Вот я тоже к этому склоняюсь. 

@antowski можно тебя попросить переименовать функцию?

2017-02-22 05:55 UTC, JohnyDeath commented
КаталогПуст, как-то звучит коряво, ИМХО

2017-02-22 05:58 UTC, dmpas commented
`ЭтотКаталогПуст` или `ЭтоПустойКаталог`

ps. `КаталогОднозначноПуст` :)

2017-02-22 06:01 UTC, artbear requested changes
Отличный PR, спасибо.
Отличные тесты.

Одно возражение - предлагаю переименовать главный метод в `ЭтоПустойКаталог`

2017-02-22 06:01 UTC, artbear commented on Модули/ФС.os
> +Функция КаталогПустой(Знач Путь) Экспорт
Предлагаю `ЭтоПустойКаталог`

2017-02-22 06:01 UTC, artbear commented on tests/КаталогПустойТест.os
> +	мМенеджерВременныхФайлов = Новый МенеджерВременныхФайлов;
Очень хорошее применение временных файлов. идеально как раз через собственый экземпляр этого класса

2017-02-22 06:05 UTC, JohnyDeath commented
> Одно возражение - предлагаю переименовать главный метод в ЭтоПустойКаталог

ИМХО, еще хуже, чем КаталогПуст. Автор хорошее название придумал, не надо ничего менять, у него уже все на этом завязано ))

2017-02-22 06:08 UTC, artbear commented
Всегда смотрим применение
`ФС.ЭтоПустойКаталог(ПутьКаталога)` хорошо смотрится.
`Ожидаем.Что(ФС.ЭтоПустойКаталог(Путь)).ЭтоИстина()` также хорошо.
что еще нужно хорошему человеку, чтобы достойно закончить пулл-реквест :) ?

2017-02-22 06:10 UTC, JohnyDeath commented
`ФС.КаталогПустой(ПутьКаталога)` плохо смотрится?

2017-02-22 06:48 UTC, nixel2007 commented
Началоооось) ладно, я сам виноват. 
@artbear предлагаю поставить зелёную галочку да смержить как есть, нечего народ пугать

2017-02-22 06:51 UTC, artbear commented
Да, я уже сам о таком же решении подумал :)

2017-02-22 06:51 UTC, artbear approved these changes

2017-02-22 06:51 UTC, merged

2017-02-22 06:51 UTC, artbear commented
@antowski Спасибо за грамотный PR :)

2017-02-22 07:03 UTC, antowski commented
Я капитан слоупок. Пока пришел всё уже обсудили и смержили.
Мне нравится как в клиентском коде читается `ФС.ЭтоПустойКаталог(Путь)`. Можно было бы сделать компромиссный вариант: добавить еще функцию
```bsl
Функция ЭтоПустойКаталог(Знач Путь) Экспорт
    Возврат КаталогПустой(Путь);
КонецФункции
```
Тогда в клиентском коде можно будет использовать оба варианта.

2017-02-22 07:06 UTC, dmpas commented
нененене, плодить одинаковые функции не дело.

2017-02-22 07:14 UTC, nixel2007 commented
Пущу волну - никто не мешает поправить прямо в девелопе! :D
/cc @artbear