Задачи 22 и 11
oscript-library/files-common pull request #23
Opened 2023-05-01 19:20 UTC by EvilBeaver

Нужны для https://github.com/oscript-library/opm/issues/208

2023-05-01 20:21 UTC, nixel2007 commented on Модули/ФС.os
> +Функция НормализоватьПуть(Знач ОтносительныйИлиПолныйПуть) Экспорт
А зачем ещё одна функция? Почему не вызвать ПолныйПуть?

2023-05-02 03:27 UTC, EvilBeaver commented on Модули/ФС.os
> +Функция НормализоватьПуть(Знач ОтносительныйИлиПолныйПуть) Экспорт
Мне название нравится, понятнее, чем ПолныйПуть. Оставил как предложение сделать такой "алиас". Разумеется, можно убрать

2023-05-02 06:13 UTC, artbear commented on Модули/ФС.os
> +Функция НормализоватьПуть(Знач ОтносительныйИлиПолныйПуть) Экспорт
> Мне название нравится, понятнее, чем ПолныйПуть. Оставил как предложение сделать такой "алиас". Разумеется, можно убрать

Мне также нравится название НормализоватьПуть, предлагаю оставить

2023-05-02 06:32 UTC, artbear requested changes

2023-05-02 06:32 UTC, artbear commented on Модули/ФС.os
> +		УдалитьФайлы(Файл.ПолноеИмя);
Не учтен кейс, когда у переданного имени файла одно расширение, а передана маска с другим расширением.

Например, ФС.УдалитьФайлы("1.txt", "*.lst");

Предлагаю
- или запретить удалять таким образом отдельные файлы, но тогда будет разница с платформенным УдалитьФайлы
- или проверять совпадение по маске\расширению
  - если передали маску как Неопределено, удалять
  - если передали нормальную маску, то проверять.

2023-05-02 06:32 UTC, artbear commented on Модули/ФС.os
> +//  Маска - Маска файлов или Неопределено, если надо удалить всё, кроме каталогов
непонятная фраза "если надо удалить всё, кроме каталогов"

1 вызов ФС.УдалитьФайлы не удаляет вложенные каталоги, так получается?

2 если должен удалять, тогда тест удаления лучше поправить на проверку удаления вложенных каталогов

2023-05-02 06:32 UTC, artbear commented on Модули/ФС.os
> +КонецФункции // ПолныйПуть(Знач ОтносительныйИлиПолныйПуть)
подобные дубль-комментарии после КонецФункции\Процедуры предлагаю удалять - я про // ПолныйПуть(Знач ОтносительныйИлиПолныйПуть)

2023-05-02 06:32 UTC, artbear commented on Модули/ФС.os
> +КонецФункции // НормализоватьПуть(Знач ОтносительныйИлиПолныйПуть) Экспорт
и тут комментарий удалить

2023-05-02 06:32 UTC, artbear commented on tests/Пути.os
> +	Ожидаем.Что(лФС.ПутиРавны(Первый, Второй)).ЭтоИстина();
не хватает кейса сравнения относительного пути через . и абсолютного пути к этому же каталогу

например, через УстановитьТекущийКаталог

2023-05-02 06:56 UTC, EvilBeaver commented on Модули/ФС.os
> +//  Маска - Маска файлов или Неопределено, если надо удалить всё, кроме каталогов
Работает как сказано в 1. Тест не удаляет каталоги, только файлы.

2023-05-02 06:57 UTC, EvilBeaver commented on tests/Пути.os
> +	Ожидаем.Что(лФС.ПутиРавны(Первый, Второй)).ЭтоИстина();
Это как?

2023-05-02 12:29 UTC, artbear commented on Модули/ФС.os
> +//  Маска - Маска файлов или Неопределено, если надо удалить всё, кроме каталогов
> Работает как сказано в 1. Метод не удаляет каталоги, только файлы.

предлагаю явно эту фразу и добавить в первое же предложение из описания метода.

например
- Удаляет рекурсивно файлы в каталоге с учетом маски, вложенные каталоги не удаляются

2023-05-02 12:31 UTC, artbear commented on Модули/ФС.os
> +//  Маска - Маска файлов или Неопределено, если надо удалить всё, кроме каталогов
@EvilBeaver ага, вижу исправление по удалению вложенных каталогов, тред закрываю

2023-05-02 12:33 UTC, artbear commented on tests/Пути.os
> +	Ожидаем.Что(лФС.ПутиРавны(Первый, Второй)).ЭтоИстина();
> Это как?

можно просто
`лФС.ПутиРавны("./папка1", ОбъединитьПути(ТекущийКаталог(), "папка1"));`

2023-05-02 12:35 UTC, artbear commented on tests/Пути.os
> +	Ожидаем.Что(лФС.ПутиРавны(Первый, Второй)).ЭтоИстина();
ну и аналогично с двумя точками в начале пути

`лФС.ПутиРавны("../fs", ОбъединитьПути(ТекущийКаталог()));`

2023-05-04 06:03 UTC, merged